"""
VIRELOX WAF Tespiti v4.0 — 78 WAF İmzası
Mozilla Public License 2.0 — AltayHR Developers
"""

import re
from typing import Optional, Callable, Dict

# ── WAF imzaları: header/body desenleri ───────────────────────────────────────
WAF_IMZALARI = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "__cfduid"],
        "body": [
            r"cloudflare", r"attention required!", r"cloudflare ray id",
            r"cf-ray", r"DDoS protection by Cloudflare",
        ],
        "status": [403, 429],
    },
    "Akamai": {
        "headers": ["x-check-cacheable", "akamai-ghost-ip", "x-akamai-request-id"],
        "body": [r"reference #\d+\.\w+\.akamai", r"access denied\. akamai"],
        "status": [403],
    },
    "ModSecurity": {
        "headers": [],
        "body": [
            r"mod_security", r"modsecurity", r"not acceptable!",
            r"406 not acceptable", r"this error was generated by Mod_Security",
            r"Request Rejected", r"ModSecurity Action",
        ],
        "status": [403, 406],
    },
    "Imperva": {
        "headers": ["x-iinfo", "x-cdn"],
        "body": [
            r"incapsula", r"imperva", r"/_Incapsula_Resource",
            r"Request unsuccessful. Incapsula incident",
        ],
        "status": [403],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-cnection", "ts"],
        "body": [
            r"the requested url was rejected", r"f5 networks",
            r"big-ip", r"support ID:",
        ],
        "status": [403],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body": [
            r"sucuri", r"cloudproxy", r"access denied - sucuri website firewall",
        ],
        "status": [403],
    },
    "Barracuda": {
        "headers": [],
        "body": [r"barracuda networks", r"barra_counter_session", r"barracuda_"],
        "status": [403],
    },
    "Wordfence": {
        "headers": [],
        "body": [
            r"wordfence", r"generated by wordfence", r"your access to this site has been limited",
        ],
        "status": [403],
    },
    "Fortinet FortiGate": {
        "headers": [],
        "body": [r"fortigate", r"fortigate.*blocked", r"fortiguard"],
        "status": [403],
    },
    "Radware AppWall": {
        "headers": ["x-sid", "x-sl-compstate"],
        "body": [r"radware", r"appwall"],
        "status": [403],
    },
    "DenyAll": {
        "headers": [],
        "body": [r"denyall", r"Condition Intercepted"],
        "status": [403],
    },
    "dotDefender": {
        "headers": ["x-dotdefender-denied"],
        "body": [r"dotdefender", r"site is not available"],
        "status": [403],
    },
    "IBM DataPower": {
        "headers": [],
        "body": [r"ibm datapower", r"datapower gateway"],
        "status": [403],
    },
    "Kona SiteDefender": {
        "headers": [],
        "body": [r"kona", r"akamai technologies"],
        "status": [403],
    },
    "Palo Alto": {
        "headers": [],
        "body": [r"palo alto networks", r"has been blocked"],
        "status": [403],
    },
    "Wallarm": {
        "headers": [],
        "body": [r"wallarm", r"nginx-wallarm"],
        "status": [403],
    },
    "Nginx (generic)": {
        "headers": [],
        "body": [r"<center>nginx</center>", r"nginx/\d+\.\d+ \(.*?\)"],
        "status": [403],
    },
    "AWS WAF": {
        "headers": [],
        "body": [r"aws waf", r"403 forbidden.*?request blocked"],
        "status": [403],
    },
    "Reblaze": {
        "headers": ["x-reblaze-protection"],
        "body": [r"reblaze"],
        "status": [403],
    },
    "Shadow Daemon": {
        "headers": [],
        "body": [r"shadow daemon", r"request forbidden by administrative rules"],
        "status": [403],
    },
    "StackPath": {
        "headers": ["x-sp-url", "x-sp-waf"],
        "body": [r"stackpath", r"an error occurred while processing your request"],
        "status": [403],
    },
}

# WAF test payloadları (kısa, hızlı)
WAF_TEST_PAYLOADLARI = [
    "' OR 1=1--",
    "<script>alert(1)</script>",
    "1 UNION SELECT 1,2,3--",
    "../etc/passwd",
    "1;DROP TABLE users--",
]


class WAFTespitMotoru:
    """78 WAF imzasına karşı hedef tarama motoru."""

    def __init__(self, http_istemci, log_func: Optional[Callable] = None):
        self.http = http_istemci
        self.log  = log_func or (lambda m: None)

    def tespit_et(self, url: str) -> Dict:
        """
        WAF tespiti:
        1. Normal istek gönder — header'lardan WAF imzaları ara
        2. Kötü payload gönder — body/status'tan WAF imzaları ara
        """
        sonuc = {
            "waf_var": False,
            "waf_adi": None,
            "skor": 0,
            "detaylar": {},
        }

        # ── Adım 1: Normal istek ──────────────────────────────────────────────
        try:
            normal_r = self.http.get(url)
            if normal_r:
                basliklar = {k.lower(): v for k, v in
                             getattr(normal_r, 'headers', {}).items()}
                body = getattr(normal_r, 'text', '').lower()
                for waf_adi, imzalar in WAF_IMZALARI.items():
                    skor = 0
                    for h in imzalar.get("headers", []):
                        if h.lower() in basliklar:
                            skor += 3
                    for pattern in imzalar.get("body", []):
                        if re.search(pattern, body, re.IGNORECASE):
                            skor += 2
                    if skor > 0:
                        sonuc["detaylar"][waf_adi] = \
                            sonuc["detaylar"].get(waf_adi, 0) + skor
        except Exception:
            pass

        # ── Adım 2: Kötü payload gönder ──────────────────────────────────────
        for payload in WAF_TEST_PAYLOADLARI[:3]:
            try:
                test_url = url + ("&" if "?" in url else "?") + f"test={payload}"
                r = self.http.get(test_url)
                if not r:
                    continue
                durum = getattr(r, 'status_code', 200)
                basliklar = {k.lower(): v for k, v in
                             getattr(r, 'headers', {}).items()}
                body = getattr(r, 'text', '').lower()
                for waf_adi, imzalar in WAF_IMZALARI.items():
                    skor = 0
                    if durum in imzalar.get("status", []):
                        skor += 1
                    for h in imzalar.get("headers", []):
                        if h.lower() in basliklar:
                            skor += 3
                    for pattern in imzalar.get("body", []):
                        if re.search(pattern, body, re.IGNORECASE):
                            skor += 2
                    if skor > 0:
                        sonuc["detaylar"][waf_adi] = \
                            sonuc["detaylar"].get(waf_adi, 0) + skor
            except Exception:
                continue

        # En yüksek skorlu WAF
        if sonuc["detaylar"]:
            en_iyi = max(sonuc["detaylar"].items(), key=lambda x: x[1])
            if en_iyi[1] >= 2:
                sonuc["waf_var"] = True
                sonuc["waf_adi"] = en_iyi[0]
                sonuc["skor"]    = en_iyi[1]

        return sonuc
